name: giftrip
description: "기프트립"

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.2
  dio: ^5.8.0+1
  logger: ^2.5.0
  flutter_secure_storage: ^9.2.4
  lucide_icons: ^0.257.0
  image_picker: ^1.1.2
  flutter_switch: ^0.3.2
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  flutter_slidable: ^4.0.0
  firebase_core: ^3.12.0
  cached_network_image: ^3.4.1
  firebase_messaging: ^15.2.3
  device_info_plus: ^11.3.0
  app_links: ^6.4.0
  android_intent_plus: ^5.3.0
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  sign_in_with_apple: ^6.1.4
  amplitude_flutter: ^4.1.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  dropdown_search: ^6.0.2
  dropdown_button2: ^2.3.9
  table_calendar: ^3.1.0
  tosspayments_widget_sdk_flutter: ^2.1.1
  flutter_inappwebview: ^6.1.5
  daum_postcode_search: ^0.0.4
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/svg/
    - assets/svg/icons/
    - assets/png/
    - assets/png/icons/
    - assets/webp/icons/
    - assets/service-terms.pdf
    - assets/privacy-policy.pdf
    - assets/fonts/Pretendard-Bold.woff
    - assets/fonts/Pretendard-SemiBold.woff
    - assets/fonts/Pretendard-ExtraBold.woff
    - assets/fonts/Pretendard-Medium.woff
    - assets/fonts/Pretendard-Regular.woff
    - assets/png/heart.png
