import 'package:giftrip/features/lodging/models/lodging_room_model.dart';

final List<LodgingRoomModel> mockRoomList = [
  LodgingRoomModel(
    accommodationId: '1',
    id: '1',
    name: '슈퍼 트윈룸',
    maxOccupancy: 2,
    checkInTime: '15:00',
    checkOutTime: '11:00',
    originalPrice: 40000,
    finalPrice: 32900,
    imageUrls: ['assets/png/room_1.png', 'assets/png/room_2.jpeg'],
    itemTags: ['트윈룸', '뷰 좋음'],
    availableFrom: DateTime.now(),
    availableTo: DateTime.now().add(const Duration(days: 30)),
    dailyStock: 10,
    isActive: true,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  LodgingRoomModel(
    accommodationId: '1',
    id: '2',
    name: '디럭스 더블룸',
    maxOccupancy: 3,
    checkInTime: '15:00',
    checkOutTime: '11:00',
    originalPrice: 50000,
    finalPrice: 45000,
    itemTags: ['더블룸', '시티뷰'],
    availableFrom: DateTime.now(),
    availableTo: DateTime.now().add(const Duration(days: 30)),
    dailyStock: 10,
    isActive: true,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    imageUrls: [
      'assets/png/room_2.jpeg',
      'assets/png/room_1.png',
    ],
  ),
];
