import 'package:giftrip/features/my/models/request_model.dart';

/// 목업 데이터
final List<RequestModel> mockRequestList = [
  RequestModel(
    id: '1',
    name: '역삼 아르누보씨티 호텔 앤 레지던스',
    date: DateTime.now().subtract(const Duration(days: 5)).toString(),
    price: 30000,
    imageUrl: 'assets/png/hotel.png',
    status: RequestStatus.cancel,
    category: CategoryType.lodging,
  ),
  RequestModel(
    id: '2',
    name: '[기프트립/전주스테이] 전주 여행 1박2일 세미체험단 관광지 음식 체험 실내 투어',
    date: DateTime.now().subtract(const Duration(days: 4)).toString(),
    price: 20000,
    imageUrl: 'assets/png/banner.png',
    status: RequestStatus.refund,
    category: CategoryType.experience,
  ),
  RequestModel(
    id: '3',
    name: '전라도 대박산 특산물 갈치속젓 300g, 1개',
    date: DateTime.now().subtract(const Duration(days: 3)).toString(),
    price: 10000,
    imageUrl: 'assets/png/shopping.png',
    status: RequestStatus.exchange,
    category: CategoryType.product,
  ),
  RequestModel(
    id: '3',
    name: '전라도 대박산 특산물 갈치속젓 300g, 1개',
    date: DateTime.now().subtract(const Duration(days: 3)).toString(),
    price: 10000,
    imageUrl: 'assets/png/shopping.png',
    status: RequestStatus.exchange,
    category: CategoryType.product,
  ),
  RequestModel(
    id: '3',
    name: '전라도 대박산 특산물 갈치속젓 300g, 1개',
    date: DateTime.now().subtract(const Duration(days: 3)).toString(),
    price: 10000,
    imageUrl: 'assets/png/shopping.png',
    status: RequestStatus.exchange,
    category: CategoryType.product,
  ),
  RequestModel(
    id: '3',
    name: '전라도 대박산 특산물 갈치속젓 300g, 1개',
    date: DateTime.now().subtract(const Duration(days: 3)).toString(),
    price: 10000,
    imageUrl: 'assets/png/shopping.png',
    status: RequestStatus.exchange,
    category: CategoryType.product,
  ),
  RequestModel(
    id: '3',
    name: '전라도 대박산 특산물 갈치속젓 300g, 1개',
    date: DateTime.now().subtract(const Duration(days: 3)).toString(),
    price: 10000,
    imageUrl: 'assets/png/shopping.png',
    status: RequestStatus.exchange,
    category: CategoryType.product,
  ),
  RequestModel(
    id: '3',
    name: '전라도 대박산 특산물 갈치속젓 300g, 1개',
    date: DateTime.now().subtract(const Duration(days: 3)).toString(),
    price: 10000,
    imageUrl: 'assets/png/shopping.png',
    status: RequestStatus.exchange,
    category: CategoryType.product,
  ),
  RequestModel(
    id: '3',
    name: '전라도 대박산 특산물 갈치속젓 300g, 1개',
    date: DateTime.now().subtract(const Duration(days: 3)).toString(),
    price: 10000,
    imageUrl: 'assets/png/shopping.png',
    status: RequestStatus.exchange,
    category: CategoryType.product,
  ),
  RequestModel(
    id: '3',
    name: '전라도 대박산 특산물 갈치속젓 300g, 1개',
    date: DateTime.now().subtract(const Duration(days: 3)).toString(),
    price: 10000,
    imageUrl: 'assets/png/shopping.png',
    status: RequestStatus.exchange,
    category: CategoryType.product,
  ),
];
